### ISSUE TITLE
Questions for Learning Engineering

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/security#91]
Hello @githubtraining/learning-engineering 👋Here is a list of the questions that I have for you about the security course. For all of these, it's OK if the answer is yes, no, or maybe someday. 👍 

### General 
- [x] Can someone please restart the dyno so our new template repo will be loaded, then close this issue? https://github.com/githubtraining/security/issues/65

### Events? 
- [x] What event can I use to watch if a user has added proper branch protections? https://github.com/githubtraining/security/pull/90 @JasonEtco 

### Getting & using relevant data
- [ ] There is a webhook for security alerts, and that data should be accessible via API. Can we get the information about what the recommended version update for a specific dependency is, and use that to validate a user's input? https://github.com/githubtraining/security/issues/14 https://github.com/githubtraining/security/issues/77#issuecomment-428838901 @JasonEtco 
- [x] Can we programmatically check if a user's repository is public or private, and give them different instructions based on that information? https://github.com/githubtraining/security/issues/52 @JamesMGreene PR open now #95 

### Flow
- [x] Can we create a branch when it becomes relevant? If not, how can we avoid the branches encouraging people to open pull requests too early in the course flow? https://github.com/githubtraining/security/issues/29 No, but maybe we should open the PRs at the beginning. @brianamarie 
- [x] If a user closes an issue when they shouldn't, should anything happen? https://github.com/githubtraining/security/issues/66
- [x] When the course is 'ready', how do we go about moving it to production behind a feature flag? 

### PDFs 
- [x] Do users actually look at the PDFs? We don't know, we'll just need to create it https://github.com/githubtraining/security/issues/26
